# Generated by Django 5.1.3 on 2025-03-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('signal_type', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'trading_signals',
            },
        ),
    ]
