# Generated by Django 5.1.3 on 2025-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradeSphere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verification_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
